# logging settings
logging:
  level:
    root: info
    org:
      apache: warn
      springframework: warn

  pattern:
    console: '%clr([%date{HH:mm:ss}]){faint} %clr(%2p) %clr(%-30.30logger{36}){cyan} %m%n%wex'

spring:
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

  cloud:
    stream:
      bindings:
        input:
          destination: orders_in
        output:
          destination: orders_out

  kafka:
    bootstrap-servers: localhost:9092
